before_install:
  - sudo add-apt-repository --yes ppa:sonkun/sfml-development
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt4-qmake libsfml-dev libphysfs-dev libtinyxml-dev libglew-dev libopenal-dev
script:
  - qmake ALTTPRemake.pro
  - make
